<a href="https://colab.research.google.com/github/thisara852/Machine-Learning-1/blob/main/info.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

In [10]:
df=pd.read_csv("/content/studentMarks.csv")

In [11]:
print(df)

    StudyHours  Attendance  AssignmentsCompleted  Marks
0            7          71                     5   93.4
1            4          93                    10   89.3
2            8          92                     0  100.0
3            5          82                     8   95.8
4            7          83                    10   99.3
..         ...         ...                   ...    ...
95          10          97                     1  100.0
96           9          83                     4   98.5
97           7          64                     0   86.2
98           9          93                     0   96.4
99           8          65                     4  100.0

[100 rows x 4 columns]

In [15]:
df.shape

(100, 4)

In [17]:
df.columns

Index(['StudyHours', 'Attendance', 'AssignmentsCompleted', 'Marks'], dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudyHours            100 non-null    int64
 1   Attendance            100 non-null    int64
 2   AssignmentsCompleted  100 non-null    int64
 3   Marks                 100 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 3.3 KB

In [20]:
df.describe()

       StudyHours  Attendance  AssignmentsCompleted       Marks
count  100.000000  100.000000            100.000000  100.000000
mean     5.910000   81.060000              4.500000   88.036000
std      2.871296   12.761068              3.179797   12.953175
min      1.000000   60.000000              0.000000   48.600000
25%      3.000000   70.000000              2.000000   80.025000
50%      6.000000   83.500000              4.000000   92.050000
75%      8.000000   92.000000              7.000000  100.000000
max     10.000000  100.000000             10.000000  100.000000

In [21]:
df['Marks'].max()

100.0

In [24]:
df.corr()

                      StudyHours  Attendance  AssignmentsCompleted     Marks
StudyHours              1.000000   -0.116738             -0.006085  0.827101
Attendance             -0.116738    1.000000             -0.149856  0.152251
AssignmentsCompleted   -0.006085   -0.149856              1.000000  0.252866
Marks                   0.827101    0.152251              0.252866  1.000000