<a href="https://colab.research.google.com/github/thisara852/Machine-Learning-1/blob/main/Missing%20Value.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd

In [32]:
df=pd.read_csv("/content/studentMarks23.csv")

In [33]:
print(df)

    StudyHours  Attendance  AssignmentsCompleted  Marks
0          7.0        71.0                   5.0   93.4
1          4.0        93.0                  10.0   89.3
2          8.0        92.0                   0.0  100.0
3          5.0        82.0                   8.0   95.8
4          7.0        83.0                  10.0   99.3
..         ...         ...                   ...    ...
95        10.0        97.0                   1.0  100.0
96         9.0        83.0                   4.0   98.5
97         7.0        64.0                   0.0   86.2
98         9.0        93.0                   0.0   96.4
99         8.0        65.0                   4.0  100.0

[100 rows x 4 columns]

In [34]:
df.isnull().sum()

StudyHours              1
Attendance              2
AssignmentsCompleted    1
Marks                   4
dtype: int64

In [35]:
df=df.dropna()

In [36]:
df=df.fillna(df.mean())

In [37]:
df=df.fillna(df.median())

In [38]:
df.isnull().sum()

StudyHours              0
Attendance              0
AssignmentsCompleted    0
Marks                   0
dtype: int64